language: node_js

node_js:
  - "6"

sudo: required

# Handle git submodules yourself
git:
    submodules: false

services:
  - docker

install:
  - docker-compose build

before_install:
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - cd server

install:
  - docker build -t jstechrelationshipsg4/relationshipsg4 .

after_success:
  - if [ "$TRAVIS_BRANCH" == "travis-docker-test" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push jstechrelationshipsg4/relationshipsg4;
    fi