language: node_js

node_js:
  - "6"

sudo: required

services:
  - docker

install:
  - docker-compose build

before_install:
  - cd server

install:
  - docker build -t jstechrelationshipsg4/relationshipsg4 .

after_success:
  - if [ "$TRAVIS_BRANCH" == "travis-docker-test" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" ;
    docker push jstechrelationshipsg4/relationshipsg4 ;
    fi